# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 陈燕山的笔记本
email: itcys@qq.com
description: > # this means to ignore newlines until "baseurl:"
  如有原创文章侵犯版权请联系,itcys@qq.com
baseurl: "/chenyanshan.github.com" # the subpath of your site, e.g. /blog
url: "http://陈燕山.top" # the base hostname & protocol for your site
twitter_username: cys_sum
github_username: chenyanshan

# Build settings
markdown: kramdown
