# Site settings
title: 陈燕山的笔记本
email: op.chenyanshan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
        邮箱: yanshanchen@hotmail.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://chenyanshan.com" # the base hostname & protocol for your site
twitter_username: sum
github_username:  chenyanshan

# Build settings
markdown: kramdown

paginate: 4

author: YanShan Chen

gems: [Jekyll-paginate]
